### ISSUE TITLE
Get sensible values as Environment Variables

### ISSUE THREAD

**Issue by falcaoaugustos** [Beakyn/release-notes-format#1]
### Current Scenario

```
- name: Relese notes format
  uses: Beakyn/release-notes-format@master
  with:
    github-token: ${{ github.token }}
    repository: ${{ github.repository }}
    milestone: ${{ github.event.inputs.milestone }}
```

### Describe the solution you'd like

```
- name: Relese notes format
  uses: Beakyn/release-notes-format@master
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    repository: ${{ github.repository }}
    milestone: ${{ github.event.inputs.milestone }}
```
